version: "3.2"

services:
  subspace:
    network_mode: host
    container_name: subspace
    build: ./
    # cpu_count: 4
    # mem_limit: 10000000000
    # memswap_limit: 20000000000
    volumes:
      # NODE BINDINGS
      - ${SUBSPACE_PATH}:/subspace
    
    command: bash -c "make deploy_chain"

    # command: bash -c "tail -f /dev/null"
